### ISSUE TITLE
[question] Service와 ServiceImpl의 분리

### ISSUE THREAD

**Issue by hjh3229** [proLmpa/NBC_Twogether#10]
다른 분들은 혹시 Service를 클래스로서 그대로 사용하시나요 아니면 ServiceImpl을 추가해서 구현하시나요? 제가 알기론 Impl을 따로 구현하는 이유가 크게 관습이며, 구현체를 수정해도 클라이언트 코드에 영향을 주지 않기 위한 원칙 때문이라고 알고있는데, 사실 지금 저희가 구현할 때 Service와 ServiceImpl이 1대1관계여서 추상화의 의미가 없다고 생각하거든요. 다른 분들 생각이 궁금합니다.

**Comment by proLmpa** [comment]
저는 인터페이스와 구현체 나눠서 구현하고 인터페이스에 주석으로 해당 기능과 매개 변수에 대한 설명을 적습니다.

**Comment by song-eojin** [comment]
회의 후 안 하기로 확정했습니다~
