### ISSUE TITLE
[refactor] 리팩토링

### ISSUE THREAD

**Issue by proLmpa** [proLmpa/NBC_Twogether#123]

**Comment by hjh3229** [comment]
알림에 스크롤바가 있으면 좋을 듯 합니다.
덱 보관 버튼의 z-index가 알림창과 알림창 문구 사이에 존재합니다.

**Comment by hjh3229** [comment]
- [x] 알림에 스크롤바가 있으면 좋을 듯 합니다.
- [x] 덱 보관 버튼의 z-index가 알림창과 알림창 문구 사이에 존재합니다.
- [x] 가끔 알림이 있는데도 '도착한 알림이 없습니다.' 문구가 뜰 때가 있습니다. 
- [x] 알림이 너무 많이 쌓였을 때 일일이 지우는 과정이 너무 번거롭습니다. 알림을 지웠다는 확인창만 지우거나 삭제 확인 자체를 지우는 게 좋을 듯 합니다.
