### ISSUE TITLE
[fix] 배포 및 머지 후 발생한 에러 처리 목록

### ISSUE THREAD

**Issue by proLmpa** [proLmpa/NBC_Twogether#125]
- [X] 카카오 로그인 안 되는 문제
- [x] 드래그 앤 드랍
- [x] 한번 보드에서 추방한 사람을 다시 초대할 수 없는 문제
  > ![스크린샷(268)](https://github.com/proLmpa/NBC_Twogether/assets/52267654/0e177ce2-283b-49f2-b59a-f86b7f478a69)

- [x] 알람 메시지에 null로 뜨는 항목들 수정하기
  > ![스크린샷(269)](https://github.com/proLmpa/NBC_Twogether/assets/52267654/93139496-bd98-475c-9eb2-6f17a8ba67f5)

**Comment by proLmpa** [comment]
- [x] 알림에 스크롤바가 있으면 좋을 듯 합니다.
- [x] 덱 보관 버튼의 z-index가 알림창과 알림창 문구 사이에 존재합니다.
- [x] 가끔 알림이 있는데도 '도착한 알림이 없습니다.' 문구가 뜰 때가 있습니다. 
- [x] 알림이 너무 많이 쌓였을 때 일일이 지우는 과정이 너무 번거롭습니다. 알림을 지웠다는 확인창만 지우거나 삭제 확인 자체를 지우는 게 좋을 듯 합니다.

**Comment by YoungDevSpace** [comment]
- [x] 워크스페이스에서 협업 멤버 초대하고 나서 추방하더라도 초대창 리스트에 협업에 초대된 멤버들이 남아있습니다.
추방 버튼을 누르면 '이미 추방된 보드 협업자입니다. '라고 뜹니다.
-> 네트워크 상태에 따라서 서버쪽으로 전달이 안된 것 같습니다~!
