### ISSUE TITLE
[notice] boolean 타입의 필드와 @Getter에 대하여

### ISSUE THREAD

**Issue by hjh3229** [proLmpa/NBC_Twogether#13]
여러분, 혹시 boolean 타입의 필드를 @Getter로 가져오려고 하면 get~~ 형식이 아닌 is~~ 형식으로 가져와야 한다는 사실을 알고 계셨나요? 저는 몰랐답니다~
참고로 이미 필드명이 is~~형식이면 필드명 그대로 가져오네요~
e.g. 
```
// Deck
@Getter
public class Deck {
...
@Column(name = "is_deleted")
private boolean isDeleted;
...

// DeckService
...
public void deleteDeck(Long id) {
...
    if (deck.isDeleted()) { 
...
```

**Comment by proLmpa** [comment]
entity 혹은 dto의 필드명에서 is를 제거하고 boolean 확인 메서드 실행 시 isDeleted()로 실행하는 게 좋습니다 !
