### ISSUE TITLE
[refactor] 현재 에러코드의 상태코드가 모두 400으로 반환되는 문제 발생

### ISSUE THREAD

**Issue by hjh3229** [proLmpa/NBC_Twogether#32]
제가 보여줬던 예시에서는 저희만의 상태코드를 반환함으로써 직관적으로 문제를 알아채기 위한 것이였는데 
`@ResponseStatus(value = HttpStatus.BAD_REQUEST)` 이 annotation 때문에 postman에서 모든 statuscode가 400으로 반환됩니다. 또한 어째선지 터미널에서도 에러코드가 반환되지 않네요.

**Comment by proLmpa** [comment]
statusCode가 400으로 반환 되는 건 CustomException을 사용하기 시작한 때부터 사용했었습니다.

그리고 터미널에 에러 코드가 반환 되지 않는 건 정상입니다. 만약 터미널에도 에러 코드를 띄우고 싶다면 @slf4j 어노테이션의 log.error()를 통해 출력하면 됩니다.

**Comment by proLmpa** [comment]
모든 컨트롤러 메서드에서 HttpServletResponse를 받는 식으로 수정하면 지훈님이 원하는 방식으로 동작 시킬 수 있습니다.

다만 아직 기능 구현이 완료되지 않았기 때문에 이후로 어떻게 변할지 알 수 없어 일단 기능 구현을 마치고 리팩토링 할 때 다뤄보면 좋을 문제인 것 같습니다.
