### ISSUE TITLE
[question] workspace 초대 와 board 초대는 어떻게 동작하면 좋을까?

### ISSUE THREAD

**Issue by proLmpa** [proLmpa/NBC_Twogether#7]
* 작업자 workspace 초대 시 : WorkspaceMember와 BoardMember 모두에 작업자 등록
 > Trello의 맹점 : 해당 작업자를 workspace에서 추방해도 하위 board에는 모두 접근할 수 있음
 > <br> 우리의 개선점 : _**workspace에서 작업자 추방 시 하위 board에서도 모두 추방하기**_

Workspace -> Board 3 -> BoardMember 3개 전부에 사용자 등록
Board -> 해당 BoardMember 사용자 등록

* WorkspaceMember entity 삭제 시 발생할 수 있는 문제점
 > 해당 Workspace에서 새로 Board를 생성하면 기존 workspace에 추가되었던 사람이 자동으로 추가되는 기능을 구현할 수 없다.
 > 지훈: 여전히 필요한 것 같다. 그리고 보드가 아예 없는 상황에서는 초대가 불가능해져요.

* 지훈 님의 의견이 수용되었습니다!(+exp 10) WorkspaceMember는 유지됩니다!

**Comment by proLmpa** [comment]
UserRoleEnum 을 workspace 를 관리하는 ADMIN과 board 를 관리하는 ADMIN 으로 구분 짓는 게 좋을까요?

**Comment by song-eojin** [comment]
[나중에 Develop 단계에서 생각해볼 만한 사항]
1. workspace에서 초대하면 자동으로 boardMember에 추가되는 로직 개선

**Comment by hjh3229** [comment]
2. role을 더 세분화(admin, user, reader)해서 admin이 다른 user의 role을 수정할 수 있는 기능 추가
