### ISSUE TITLE
[update] h2를 사용한 테스트 코드 작성

### ISSUE THREAD

**Issue by hjh3229** [proLmpa/NBC_Twogether#76]
h2를 사용해 테스트 코드를 작성해보려고 한다.

h2를 사용하는 이유
1. 컴퓨터에 저장된 RAM 기반 RDBMS여서 용량이 적고, 브라우저 기반 콘솔을 지원한다.
2. spring boot에서는 별도의 db를 사용하지 않고 사용할 수 있다.

**Comment by proLmpa** [comment]
h2를 사용하지 않고 mysql로 먼저 진행하기로 했습니다.

**Comment by proLmpa** [comment]
MySQL 8.0에서 테이블 생성 시 주의해야 할 예약어에 User도 포함되기 때문에 User entity의 테이블 명을 'users'로 수정했습니다.

참고 출처 : https://okky.kr/questions/1364909

**Comment by proLmpa** [comment]
애플리케이션 실행 환경의 application.properties와 별개로 test 환경에 application.yml을 별도 추가

**Comment by proLmpa** [comment]
## 서비스 테스트 코드 진행 상황
- [X] User
- [ ] Workspace 
- [ ] Board
- [X] Deck
- [X] Card
